<a href="https://colab.research.google.com/github/Jayameena832/ML-behind-the-curtains/blob/main/ML_stamatics_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import math

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
y = np.full_like(x,1)

In [ ]:
print(y)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
x = np.array([[1,2],[3,4]])
arr = x

In [ ]:
print(arr)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
x = np.linspace(3,10,50)

In [ ]:
print(x)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = x.reshape(2,-1).ravel('f')

In [ ]:
print(y)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1,10)
print("Before split",x)
y = np.split(x,[4,6])
print("After split",y)

Before split [1 2 3 4 5 6 7 8 9]
After split [array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
z = np.trace(x)

In [ ]:
print(y)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(z)

5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x = np.array([[1,4],[3,1]])
y = np.argsort(x,axis=1)

In [ ]:
print(y)

[[0 1]
 [1 0]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
from numpy.lib.shape_base import take_along_axis
x = np.array([[1,4],[3,1]])
y = np.argsort(x,axis=1)
z = np.take_along_axis(x, y, axis = 1)

In [ ]:
print(z)

[[1 4]
 [1 3]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.random_integers(9+1,size=(2,5))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
print(x)

[[6 6 2 5 7]
 [5 5 7 7 9]]


In [ ]:
max = np.amax(x)
max_index = np.where(x == np.amax(x))

In [ ]:
print(max)
print(max_index)

9
(array([1]), array([4]))


In [ ]:
min = np.amin(x)
min_index = np.where(x == np.amin(x))

In [ ]:
print(min)
print(min_index)

2
(array([0]), array([2]))


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Drop rows that contain a missing value. 

In [ ]:
df = pd.DataFrame(iris_2d, columns = ['a','b','c','d'])
print(df.dropna())

       a    b    c    d
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
df.isnull().values.any()

False

Find the correlation between first two columns.

In [ ]:
column_1 = df["a"]
column_2 = df["b"]
correlation = column_1.corr(column_2)

In [ ]:
print(correlation)

-0.10936924995064937


Find the mean,median and standard deviation of column 3.

In [ ]:
m = df["c"].mean()
print(m)

3.7586666666666693


In [ ]:
med = df["c"].median()
print(med)

4.35


In [ ]:
standard_dev = df["c"].std()
print(standard_dev)

1.7644204199522617


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
petallength = df.loc[:,"c"]
sepal_length = df.loc[:,"a"]
volume = (((math.pi)*(petallength)*(sepal_length**2))/3)
df.insert(5,"volume",[volume],[150])

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
df1 = pd.DataFrame(iris, columns = ['sepallength','sepalwidth','petallength','petalwidth','species'])

In [ ]:
print(df1)

    sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]


Find the count of unique species.

In [ ]:
print(df1['species'].value_counts())

b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: species, dtype: int64


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
petal_length_bin = np.digitize('petallength')
new_value = [ if x<3 :'small', else if 3<x<5 : 'medium',else x>5 :'large' for x in ['petallength']]

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
print(df1['petallength'].mode())

0    b'1.5'
dtype: object
